version: '3'

volumes:
  pg_data_taski:
  static:

services:
  db_taski:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_taski:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db_taski
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80